import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/Menu'
import Orders from '@/components/Orders'
import { OrdersProvider } from '@/context/OrdersContext';
import Counter from '@/components/Counter'
import { CounterProvider } from '@/context/CounterContext'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className="header">
          <h1>Coffee Shop Technical Interview</h1>
          <p>Details</p>
          <ol>
            <li>Populates a drink menu from some data, in a real scenario this data is returned from an API call</li>
            <li>Each drink has a duration value, which is the time in seconds it takes to make each drink</li>
            <li>When a customer clicks a drink item, it is added to the baristas queue (Orders)</li>
            <li>The barista can only make one drink at a time</li>
            <li>When the drink is finished, it is placed on the counter (Counter) for pickup.</li>
            <li>Each drink is picked up 3 seconds after it is placed on the counter.</li>
          </ol>
        </header>

        <div className={styles.grid}>
          <OrdersProvider>
            <CounterProvider> 
              <Menu />
              <Orders />
              <Counter />
            </CounterProvider>
          </OrdersProvider>
        </div>
      </main>
    </>
  )
}
